
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARROW ASSIGN COMPLEMENT GC IDENTIFIER PRINT REVERSE SEQUENCE STRING TRANSCRIBE TRANSLATE\nprogram : statements\n\nstatements : statements statement\n\nstatements : statement\n\nstatement : SEQUENCE IDENTIFIER ASSIGN STRING\n\nstatement : TRANSCRIBE IDENTIFIER ARROW IDENTIFIER\n\nstatement : TRANSLATE IDENTIFIER ARROW IDENTIFIER\n\nstatement : REVERSE IDENTIFIER ARROW IDENTIFIER\n\nstatement : COMPLEMENT IDENTIFIER ARROW IDENTIFIER\n\nstatement : GC IDENTIFIER ARROW IDENTIFIER\n\nstatement : PRINT IDENTIFIER\n'
    
_lr_action_items = {'SEQUENCE':([0,2,3,11,18,25,26,27,28,29,30,],[4,4,-3,-2,-10,-4,-5,-6,-7,-8,-9,]),'TRANSCRIBE':([0,2,3,11,18,25,26,27,28,29,30,],[5,5,-3,-2,-10,-4,-5,-6,-7,-8,-9,]),'TRANSLATE':([0,2,3,11,18,25,26,27,28,29,30,],[6,6,-3,-2,-10,-4,-5,-6,-7,-8,-9,]),'REVERSE':([0,2,3,11,18,25,26,27,28,29,30,],[7,7,-3,-2,-10,-4,-5,-6,-7,-8,-9,]),'COMPLEMENT':([0,2,3,11,18,25,26,27,28,29,30,],[8,8,-3,-2,-10,-4,-5,-6,-7,-8,-9,]),'GC':([0,2,3,11,18,25,26,27,28,29,30,],[9,9,-3,-2,-10,-4,-5,-6,-7,-8,-9,]),'PRINT':([0,2,3,11,18,25,26,27,28,29,30,],[10,10,-3,-2,-10,-4,-5,-6,-7,-8,-9,]),'$end':([1,2,3,11,18,25,26,27,28,29,30,],[0,-1,-3,-2,-10,-4,-5,-6,-7,-8,-9,]),'IDENTIFIER':([4,5,6,7,8,9,10,20,21,22,23,24,],[12,13,14,15,16,17,18,26,27,28,29,30,]),'ASSIGN':([12,],[19,]),'ARROW':([13,14,15,16,17,],[20,21,22,23,24,]),'STRING':([19,],[25,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser.py',24),
  ('statements -> statements statement','statements',2,'p_statements_multiple','parser.py',35),
  ('statements -> statement','statements',1,'p_statements_single','parser.py',42),
  ('statement -> SEQUENCE IDENTIFIER ASSIGN STRING','statement',4,'p_statement_sequence','parser.py',53),
  ('statement -> TRANSCRIBE IDENTIFIER ARROW IDENTIFIER','statement',4,'p_statement_transcribe','parser.py',64),
  ('statement -> TRANSLATE IDENTIFIER ARROW IDENTIFIER','statement',4,'p_statement_translate','parser.py',75),
  ('statement -> REVERSE IDENTIFIER ARROW IDENTIFIER','statement',4,'p_statement_reverse','parser.py',86),
  ('statement -> COMPLEMENT IDENTIFIER ARROW IDENTIFIER','statement',4,'p_statement_complement','parser.py',97),
  ('statement -> GC IDENTIFIER ARROW IDENTIFIER','statement',4,'p_statement_gc','parser.py',108),
  ('statement -> PRINT IDENTIFIER','statement',2,'p_statement_print','parser.py',119),
]
